#
# Copyright (C) 2022 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/infinix/X6886

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic

# Power
ENABLE_CPUSETS := true
ENABLE_SCHEDBOOST := true

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := X6886
TARGET_NO_BOOTLOADER := true

# Build hacks
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true

# DTBO
BOARD_KERNEL_SEPARATED_DTBO := true

# Kernel
TARGET_NO_KERNEL := true
BOARD_RAMDISK_USE_LZ4 := true
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb.img

BOARD_BOOT_HEADER_VERSION := 4
BOARD_KERNEL_BASE := 0x3fff8000
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_KERNEL_TAGS_OFFSET := 0x07c88000
BOARD_PAGE_SIZE := 4096
BOARD_TAGS_OFFSET := 0x07c88000
BOARD_RAMDISK_OFFSET := 0x26f08000
BOARD_DTB_SIZE := 209018
BOARD_DTB_OFFSET := 0x07c88000
BOARD_VENDOR_BASE := 0x3fff8000
BOARD_VENDOR_CMDLINE := bootopt=64S3,32N2,64N2

BOARD_MKBOOTIMG_ARGS += --dtb $(TARGET_PREBUILT_DTB)
BOARD_MKBOOTIMG_ARGS += --vendor_cmdline $(BOARD_VENDOR_CMDLINE)
BOARD_MKBOOTIMG_ARGS += --pagesize $(BOARD_PAGE_SIZE) --board ""
BOARD_MKBOOTIMG_ARGS += --kernel_offset $(BOARD_KERNEL_OFFSET)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --dtb_offset $(BOARD_DTB_OFFSET)

# AVB
BOARD_AVB_ENABLE := true

# Partitions configs
BOARD_FLASH_BLOCK_SIZE := 262144 # (BOARD_KERNEL_PAGESIZE * 64)
BOARD_MAIN_SIZE := 12670140416
BOARD_SUPER_PARTITION_SIZE := 9126805504 # TODO: Fix hardcoded value
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_USES_METADATA_PARTITION := true
BOARD_SUPER_PARTITION_GROUPS := main
BOARD_MAIN_PARTITION_LIST += \
    odm_dlkm \
    product \
    system \
    system_ext \
    vendor \
    vendor_dlkm

BOARD_ODM_DLKMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDOR_DLKMIMAGE_FILE_SYSTEM_TYPE := ext4

TARGET_COPY_OUT_ODM_DLKM := odm_dlkm
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_SYSTEM := system
TARGET_COPY_OUT_SYSTEM_EXT := system_ext
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_VENDOR_DLKM := vendor_dlkm

# Platform
TARGET_BOARD_PLATFORM := mt6789

# Properties
TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop

# Recovery
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_USES_GENERIC_KERNEL_IMAGE := true
BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
TARGET_NO_RECOVERY := true
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/root/system/etc/recovery.fstab
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# Crypto
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_USE_FSCRYPT_POLICY := 2
TW_FORCE_KEYMASTER_VER := 4
OF_DEFAULT_KEYMASTER_VERSION := 4

# The path to a temperature sensor
TW_CUSTOM_CPU_TEMP_PATH := "/sys/devices/virtual/thermal/thermal_zone19/temp"

# Hack
PLATFORM_SECURITY_PATCH := 2099-06-05
PLATFORM_VERSION := 15
PLATFORM_VERSION_LAST_STABLE := $(PLATFORM_VERSION)
VENDOR_SECURITY_PATCH := $(PLATFORM_SECURITY_PATCH)
BOOT_SECURITY_PATCH := $(PLATFORM_SECURITY_PATCH)

# Tools
TW_INCLUDE_FB2PNG := true
TW_INCLUDE_NTFS_3G := true
TW_INCLUDE_REPACKTOOLS := true
TW_INCLUDE_RESETPROP := true
TW_INCLUDE_LPTOOLS := true

# F2FS
TW_ENABLE_FS_COMPRESSION := false

# Debug
TARGET_USES_LOGD := true
TWRP_INCLUDE_LOGCAT := true
TARGET_RECOVERY_DEVICE_MODULES += debuggerd
RECOVERY_BINARY_SOURCE_FILES += $(TARGET_OUT_EXECUTABLES)/debuggerd
TARGET_RECOVERY_DEVICE_MODULES += strace
RECOVERY_BINARY_SOURCE_FILES += $(TARGET_OUT_EXECUTABLES)/strace

# Fastbootd
TW_INCLUDE_FASTBOOTD := true

# TWRP Configs
TW_EXCLUDE_APEX := true
TW_EXCLUDE_LPDUMP := true
TW_EXTRA_LANGUAGES := true
TW_NO_SCREEN_BLANK := true
TW_SCREEN_BLANK_ON_BOOT := true
TARGET_USES_MKE2FS := true
TW_LOAD_VENDOR_BOOT_MODULES := true

# Hack depends
ALLOW_MISSING_DEPENDENCIES := true

# Assert
TARGET_OTA_ASSERT_DEVICE := Infinix-X6886

# Display
TARGET_SCREEN_DENSITY := 392
TW_FRAMERATE := 144
TW_THEME := portrait_xhdpi
TW_BRIGHTNESS_PATH := /sys/class/leds/lcd-backlight/brightness
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 128
TW_STATUS_ICONS_ALIGN := center
TW_CUSTOM_CPU_POS := 50
TW_CUSTOM_CLOCK_POS := 300
TW_CUSTOM_BATTERY_POS := 800

# Init
TARGET_INIT_VENDOR_LIB := libinit_Infinix-X6886
TARGET_RECOVERY_DEVICE_MODULES += libinit_Infinix-X6886

# TWRP Configs
TW_DEVICE_VERSION := BeRu

# ========== OUR ADDITIONS ==========

# 64-bit support
TARGET_SUPPORTS_64_BIT_APPS := true

# Display - OrangeFox R12.1
TARGET_SCREEN_WIDTH := 1224
TARGET_SCREEN_HEIGHT := 2720
TW_ROTATION := 0
TW_EXCLUDE_TWRP_DEFAULT_KEYMAP := true
OF_SCREEN_H := 2720
OF_STATUS_H := 100
OF_STATUS_INDENT_LEFT := 70
OF_STATUS_INDENT_RIGHT := 70
OF_CLOCK_POS := right
OF_ALLOW_DISABLE_NAVBAR := 1
OF_HIDE_NOTCH := 1
OF_DISPLAY_120HZ_SUPPORT := 1
OF_DISPLAY_144HZ_SUPPORT := 1

# OrangeFox Features
OF_USE_LZMA_COMPRESSION := 1
OF_USE_ICON_BITMAP := 1
OF_THEME := dark

# Flashlight
OF_FL_PATH1 := /sys/class/leds/flashlight/brightness
OF_FL_PATH2 := /sys/class/leds/led:torch_0/brightness

# Encryption - Auto decrypt on boot
OF_FIX_DECRYPTION_ON_DATA_MEDIA := 1
OF_KEEP_DM_VERITY_FORCE_ENCRYPTION := 1
OF_SKIP_FBE_DECRYPTION := 0
OF_DONT_PATCH_ENCRYPTED_DEVICE := 1
OF_FORCE_DECRYPT_ON_BOOT := 1

# Security
OF_ADVANCED_SECURITY := 1
OF_USE_MAGISKBOOT := 1
OF_USE_MAGISKBOOT_FOR_ALL_PATCHES := 1

# Misc OrangeFox
OF_NO_MIUI_PATCH_WARNING := 1
OF_NO_TREBLE_CHECK := 1
OF_DISABLE_MIUI_SPECIFIC_FEATURES := 1
OF_AB_DEVICE_WITH_RECOVERY_PARTITION := 1
OF_UNMOUNT_DATA_FIRST := 1

# MTP & USB
TW_INCLUDE_MTP := true
TW_HAS_MTP := true
TW_MTP_DEVICE := /dev/mtp_usb
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_USE_MODEM_HARDWARE_KEY := true

# FRP
TW_INCLUDE_FRP := true

# KernelSU
TW_INCLUDE_KERNELSU := true

# File system tools
TW_INCLUDE_EXFAT := true
TW_INCLUDE_FUSE_EXFAT := true
TW_INCLUDE_FUSE_NTFS := true
TW_INCLUDE_PYTHON := true

# Debug
TW_EXTRA_EVENT_LOG_ENABLED := true
TW_INCLUDE_CRYPTO_UMS := true

# Misc
TW_USE_NEW_MINADBD := true
TW_NO_LEGACY_PROPS := true
TW_DATA_RECOVERY := true
BOARD_SUPPRESS_SECURE_ERASE := true

# External SD
TW_EXTERNAL_STORAGE_PATH := "/external_sd"
TW_EXTERNAL_STORAGE_PREFIX := "/external_sd"

# Maintainer
OF_MAINTAINER := B E R U

# Suppress metadata mount errors
OF_FBE_METADATA_MOUNT_IGNORE := 1

# Settings persistence (uses /cache which is always accessible)
FOX_SETTINGS_ROOT_DIRECTORY := /cache

# Vibrator
OF_SUPPORT_VIBRATOR := 1
TW_CUSTOM_VIBRATOR_PATH := "/sys/class/leds/vibrator/brightness"

# Extra OrangeFox goodies
OF_ENABLE_FRP_ADDON := 1
OF_DISABLE_OTA_MENU := 1
OF_USE_GREEN_LED := 1
OF_DISABLE_ORS_AUTO_REBOOT := 1
OF_NO_SPLASH_CHANGE := 1

# Extra tools
TW_INCLUDE_LIBRESETPROP := true
TW_CRYPTO_USE_FBE := true
TW_CRYPTO_FBE := true

# Performance
TW_LOAD_VENDOR_MODULES := true
TW_USE_TOOLBOX := true
